CREATE TABLE TRASHCATHEGORY (
    id int AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50)

);


CREATE TABLE TRASH(
    id int  AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    trash_cathegory_id int REFERENCES TRASHCATHEGORY(id)

);

CREATE TABLE TRASHCAN(
    id int AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    trash_cathegory_id int REFERENCES TRASHCATHEGORY(id)
);

